import React, { useState } from 'react';
import { X, Github, Loader2, Check, ArrowRight, GitBranch, Lock, Globe } from 'lucide-react';
import { useApp } from '../../../providers/app-provider';

export const GithubModal = () => {
  const { isGithubModalOpen, setIsGithubModalOpen, generatedCode } = useApp();
  const [step, setStep] = useState<'connect' | 'form' | 'pushing' | 'success'>('connect');
  const [repoName, setRepoName] = useState('my-vibethera-project');
  const [isPrivate, setIsPrivate] = useState(false);

  if (!isGithubModalOpen) return null;

  const handleConnect = () => {
    // Simulate auth delay
    setTimeout(() => setStep('form'), 1000);
  };

  const handlePush = () => {
    setStep('pushing');
    // Simulate push delay
    setTimeout(() => setStep('success'), 2000);
  };

  const handleClose = () => {
    setIsGithubModalOpen(false);
    // Reset after transition
    setTimeout(() => setStep('connect'), 300);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-[fadeIn_0.2s_ease-out]">
        <div className="w-full max-w-md bg-[#1a1a1a] border border-[#333] rounded-xl shadow-2xl overflow-hidden flex flex-col">
            {/* Header */}
            <div className="h-14 border-b border-[#333] flex items-center justify-between px-6 bg-[#141414]">
                <div className="flex items-center space-x-2">
                    <Github className="w-5 h-5 text-white" />
                    <span className="font-medium text-white">Push to GitHub</span>
                </div>
                <button onClick={handleClose} className="text-gray-400 hover:text-white transition-colors">
                    <X className="w-5 h-5" />
                </button>
            </div>

            {/* Content */}
            <div className="p-6">
                {step === 'connect' && (
                    <div className="text-center space-y-6 py-4">
                        <div className="w-16 h-16 bg-[#24292e] rounded-full mx-auto flex items-center justify-center">
                             <Github className="w-8 h-8 text-white" />
                        </div>
                        <div>
                            <h3 className="text-lg font-medium text-white mb-2">Connect GitHub Account</h3>
                            <p className="text-sm text-gray-400">Link your account to create repositories and push code directly from Vibethera.</p>
                        </div>
                        <button 
                            onClick={handleConnect}
                            className="w-full py-2.5 bg-[#24292e] hover:bg-[#2f363d] text-white rounded-lg font-medium transition-colors flex items-center justify-center space-x-2"
                        >
                            <Github className="w-4 h-4" />
                            <span>Connect GitHub</span>
                        </button>
                    </div>
                )}

                {step === 'form' && (
                    <div className="space-y-4">
                         <div>
                            <label className="block text-xs font-medium text-gray-400 mb-1.5">Repository Name</label>
                            <input 
                                type="text" 
                                value={repoName}
                                onChange={(e) => setRepoName(e.target.value)}
                                className="w-full bg-[#0a0a0a] border border-[#333] rounded-lg px-3 py-2 text-white focus:outline-none focus:border-blue-500 transition-colors placeholder:text-gray-600"
                                placeholder="my-awesome-project"
                            />
                        </div>
                        <div>
                            <label className="block text-xs font-medium text-gray-400 mb-1.5">Description (Optional)</label>
                            <textarea 
                                className="w-full bg-[#0a0a0a] border border-[#333] rounded-lg px-3 py-2 text-white focus:outline-none focus:border-blue-500 transition-colors h-20 resize-none placeholder:text-gray-600"
                                placeholder="Generated by Vibethera..."
                            />
                        </div>
                        
                        <div className="flex items-center justify-between py-2">
                            <div className="flex items-center space-x-2">
                                {isPrivate ? <Lock className="w-4 h-4 text-amber-400" /> : <Globe className="w-4 h-4 text-green-400" />}
                                <span className="text-sm text-white">{isPrivate ? 'Private Repository' : 'Public Repository'}</span>
                            </div>
                            <button 
                                onClick={() => setIsPrivate(!isPrivate)}
                                className={`relative inline-flex items-center h-5 rounded-full w-9 transition-colors ${isPrivate ? 'bg-blue-600' : 'bg-[#333]'}`}
                            >
                                <span className={`inline-block w-4 h-4 transform bg-white rounded-full transition-transform ${isPrivate ? 'translate-x-4' : 'translate-x-1'}`} />
                            </button>
                        </div>

                        <button 
                            onClick={handlePush}
                            disabled={!generatedCode}
                            className="w-full mt-4 py-2.5 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg font-medium transition-colors flex items-center justify-center space-x-2"
                        >
                            <GitBranch className="w-4 h-4" />
                            <span>Create & Push</span>
                        </button>
                        {!generatedCode && <p className="text-xs text-center text-red-400">Generate some code first!</p>}
                    </div>
                )}

                {step === 'pushing' && (
                    <div className="text-center space-y-6 py-8">
                         <Loader2 className="w-12 h-12 text-blue-500 animate-spin mx-auto" />
                         <div>
                             <h3 className="text-white font-medium">Pushing to GitHub...</h3>
                             <p className="text-sm text-gray-400 mt-2">Creating repository and uploading files.</p>
                         </div>
                    </div>
                )}

                {step === 'success' && (
                    <div className="text-center space-y-6 py-4">
                        <div className="w-16 h-16 bg-green-500/10 rounded-full mx-auto flex items-center justify-center border border-green-500/20">
                             <Check className="w-8 h-8 text-green-500" />
                        </div>
                        <div>
                            <h3 className="text-lg font-medium text-white mb-2">Successfully Pushed!</h3>
                            <p className="text-sm text-gray-400">Your project is now live on GitHub.</p>
                        </div>
                        
                        <div className="bg-[#0a0a0a] border border-[#333] rounded-lg p-3 flex items-center justify-between group cursor-pointer hover:border-gray-500 transition-colors" onClick={() => window.open(`https://github.com/username/${repoName}`, '_blank')}>
                            <div className="flex items-center space-x-2 text-sm">
                                <Github className="w-4 h-4 text-gray-400" />
                                <span className="text-blue-400 hover:underline">username/{repoName}</span>
                            </div>
                            <ArrowRight className="w-4 h-4 text-gray-500 group-hover:text-white" />
                        </div>

                        <button 
                            onClick={handleClose}
                            className="w-full py-2.5 bg-[#333] hover:bg-[#444] text-white rounded-lg font-medium transition-colors"
                        >
                            Done
                        </button>
                    </div>
                )}
            </div>
        </div>
    </div>
  );
};